### ISSUE TITLE
New installation failed @revolist/vue3-datagrid 

### ISSUE THREAD

**Issue by ghost** [revolist/revogrid#231] opened 2021-07-10 04:23 UTC
Hello everyone, I am doing a new installation, I go from Vue 2 to Vue 3 but it generates these errors

Uncaught TypeError: can't access property "emit", this.beforecolumnsset is undefined

TypeError: can't access property "registerElement", this.scrollingService is undefined

I have already installed @revolist/vue3-datagrid, but I can't find what can be wrong, I hope you can help me.

**Comment by ianoble** [comment] 2021-07-20 20:51
Same exact thing for me too...

**Comment by wglas85** [comment] 2021-07-21 10:12
This is a duplicate of https://github.com/revolist/vue3-datagrid/issues/5 and is supposedly fixed by our pull request https://github.com/revolist/vue3-datagrid/pull/6

**Comment by ianoble** [comment] 2021-07-21 16:32
Any idea when that PR will be merged and released?

**Comment by wglas85** [comment] 2021-07-21 18:06
Up to now we have no reaction from the maintainer, we'd like this one to be released, too.

**Comment by wglas85** [comment] 2021-07-22 14:56
The PR has been merged by the maintainer and released as vue3-datagrid version 3.0.96
Please verify the fix and close this issue afterwards.

**Closed** 2024-07-11 16:00 UTC
